apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kuryrsecuritygroups.openstack.org
spec:
  group: openstack.org
  scope: Namespaced
  names:
    plural: kuryrsecuritygroups
    singular: kuryrsecuritygroup
    kind: KuryrSecurityGroup
    shortNames:
      - ksg
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - endpointName
              properties:
                endpointName:
                  type: string
            status:
              type: object
              required:
                - securityGroupIDs
              properties:
                securityGroupIDs:
                  type: array
                  items:
                    type: string
                endpointResourceVersoin:
                  type: string
      additionalPrinterColumns:
         - name: EndpointName
           type: string
           description: endpoint name
           jsonPath: .spec.endpointName
